export const profileQueryKeys = {
  CLIENT_PROFILE: "CLIENT_PROFILE",
  CLIENT_COMPANY_SIZE: "CLIENT_COMPANY_SIZE",
  SERVICES_ACTIVE: "SERVICES_ACTIVE",
  INDUSTRY_PUBLIC: "INDUSTRY_PUBLIC",
  WORK_MODE_FILTER: ""
}